import { Router } from 'express';
import { requestOtpHandler, verifyOtpHandler, resendOtpHandler } from '../controllers/otp.controller';
import { validate } from '../middleware/validate';
import { requestOtpSchema, verifyOtpSchema, resendOtpSchema } from '../validation/otp.validation';
import rateLimit from 'express-rate-limit';
const otpLimiter = rateLimit({ windowMs: 15*60*1000, max: 20, message: { success:false, message:'Too many OTP requests. Please try later.' } });
const router = Router();
router.post('/request', otpLimiter, validate(requestOtpSchema), requestOtpHandler);
router.post('/verify', otpLimiter, validate(verifyOtpSchema), verifyOtpHandler);
router.post('/resend', otpLimiter, validate(resendOtpSchema), resendOtpHandler);
export default router;